apiVersion: apps/v1
kind: Deployment
metadata:
  name: grid-deploy
  labels:
    app: grid-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grid-app
  template:
    metadata:
      labels:
        app: grid-app
    spec:
      containers:
        - name: grid-container
          image: grid
          ports:
            - containerPort: 5173
