apiVersion: v1
kind: Service
metadata:
  name: grid-service
  labels:
    app: grid-app
spec:
  selector:
    app: grid-app
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 5173
      nodePort: 30100
  type: NodePort
